### ISSUE TITLE
[Bug]:  Global search on root resources throws exception

### ISSUE THREAD

**Issue by acepoblete** [GuavaCZ/filament-nested-resources#10]
### What happened?

Using global search on a root resource throws an error.

### How to reproduce the bug

Configure a column to be globally searchable on the root resource.  Then search for a record in that resource.

### Package Version

1.0.0-alpha.6

### PHP Version

^8.1

### Laravel Version

^10

### Notes

I'm not sure if this is a user error or not.  When I set up my root resource I didn't override the getAncestors method; it still returns null. So, when the `getGlobalSearchResultUrl` method is called on the `NestedResource` and it tries to search through its ancestors for their ids things blow up.

**Comment by lukas-frey** [comment]
Hi! Thanks a lot, It's fixed in the new release!

**Comment by acepoblete** [comment]
@lukas-frey any reason why you default to the edit views instead of the view pages?

**Comment by lukas-frey** [comment]
> @lukas-frey any reason why you default to the edit views instead of the view pages?

Just made more sense to me. When you don't have permission for the edit page, it goes to the view page.

For example, if you have 2 roles: Admin and User, where Admin has permission to view and edit, while user only has permission to view, it made more sense to me that the admin should default to edit (since that's probably what he's most working with) and the user defaulting to view.
