### ISSUE TITLE
[Bug]: getBreadcrumbs gives error when a field is refreshing

### ISSUE THREAD

**Issue by teodino93** [GuavaCZ/filament-nested-resources#25]
### What happened?

If a field is live, when it is updated in a CreateRelatedRecord a "Typed property Guava\FilamentNestedResources\Pages\CreateRelatedRecord::$record must not be accessed before initialization" error is raised.

### How to reproduce the bug

Set a field as live() and change its status.

### Package Version

1.0.0-beta.3

### PHP Version

8.2.16

### Laravel Version

10.48.3

### Notes

Changing
$record = $this->record
with
$record = isset($this->record)
            ? $this->record
            : $this->getOwnerRecord();
resolved the problem for me

**Comment by lukas-frey** [comment]
Hello @teodino93, thank you for the bug report! I'll look into it.

This is the one single class which is quite hacky so I guess there's going to be quite a few bugs there that I've missed. :-)

**Comment by lukas-frey** [comment]
Thanks a lot for the suggestion, it's fixed in [1.0.0-beta.4](https://github.com/GuavaCZ/filament-nested-resources/releases/tag/1.0.0-beta.4)!

**Comment by teodino93** [comment]
Thank you! I wanted to ask if the nested URL is going to be in the project again (beta broke the routing), but I can't see a page where to do so. Sorry if I'm mistaken, keep up the good work!

**Comment by lukas-frey** [comment]
> Thank you! I wanted to ask if the nested URL is going to be in the project again (beta broke the routing), but I can't see a page where to do so. Sorry if I'm mistaken, keep up the good work!

Hi, this was sadly an intentional choice.

Making the URLs work was a major point causing all the issues and prevented us from implementing recursive nestable resources (nesting resources of the same type, such as Comment -> Comment -> Comment for example).

Removing nested URLs made the codebase a lot simpler and more flexible, so currently there's no plan on adding them back.

EDIT: We were able to keep it in the breadcrumbs though.
