### ISSUE TITLE
[Bug]: scope to tenant not respected on nested resource

### ISSUE THREAD

**Issue by jamessessford** [GuavaCZ/filament-nested-resources#29]
### What happened?

When I create a record of a nested resource - in this case a page which is nested to a document - I get a 500 error as team_id isn't present on the nested resource table.

Documents are scoped to tenants but pages don't have to be as they belong to documents. 

### How to reproduce the bug

Create a resource and a nested resource. Set scopedToTenant as false on the nested resource.

### Package Version

1.0.0

### PHP Version

8.3

### Laravel Version

10

### Which operating systems does with happen with?

macOS

### Notes

I may be using the package wrong and if so please let me know what I should've done differently.

Thanks for an excellent plugin!

**Comment by lukas-frey** [comment]
@jamessessford Hi, thanks for the bug report. Can you provide a test repository with the bug? I tried reproducing it as you described and I can disable tenant scoping without an issue.

**Comment by jamessessford** [comment]
I will bud! Is there any chance you can put the test repo you've made up to see if I've just made a mistake?

**Comment by jamessessford** [comment]
Sorry it took a little longer than I expected @lukas-frey - the test repo is available at https://github.com/jamessessford/nested-resource-bug

**Comment by lukas-frey** [comment]
> Sorry it took a little longer than I expected @lukas-frey - the test repo is available at https://github.com/jamessessford/nested-resource-bug

Thanks for the repo. The issue is that you're trying to set one of the child nested resources (not the root nested resource) as not scoped. However, since the `CreateDocumentPage` is a `DocumentResource` page, not a `PageResource` page, it uses the `isScopedToTenant` setting from DocumentResource, not PageResource (CreateRelatedRecord class line 184).

Currently there's no easy way for me to know the related resource without introducing another property you need to manually set in each page, which is not something I'm too inclined to do right now.

What's the use case actually here? Why do you need to disable scoping on the PageResource? It belongs to a document, which is scoped to a tenant anyways, so it will still be scoped to a tenant via this relationship. Is it really necessary to have it disabled? Maybe I'm missing something.

Anyways, your best bet for now is to override the `handleRecordCreation` method in your `CreateDocumentPage` class and replace the `static::getResource()` call with the actual resource (PageResource) in your case.

**Comment by jamessessford** [comment]
Thanks for checking it out @lukas-frey

> What's the use case actually here? Why do you need to disable scoping on the PageResource? It belongs to a document, which is scoped to a tenant anyways, so it will still be scoped to a tenant via this relationship. Is it really necessary to have it disabled? Maybe I'm missing something.

Not entirely needed no - I'm was just trying to keep the database smaller and because a document already belonged to a tenant, it seemed a wasted field to also include it on the pages. They can only be browsed via the `DocumentResource` so didn't need to be scoped.

> Anyways, your best bet for now is to override the handleRecordCreation method in your CreateDocumentPage class and replace the static::getResource() call with the actual resource (PageResource) in your case.

Thanks, I'll give this a shot when I'm looking at it again.

**Comment by jamessessford** [comment]
@lukas-frey - I think I've fixed this in my local version - are you happy if I raise a pull request for you to have a look at?

**Comment by lukas-frey** [comment]
> @lukas-frey - I think I've fixed this in my local version - are you happy if I raise a pull request for you to have a look at?

Sure, you're more than welcome to create a PR and I'll have a look! :)

**Comment by jamessessford** [comment]
Thanks, @lukas-frey

#32
